name: KBingo
version: ${project.version}
main: yt.lost.main.KBingo
api-version: 1.16
commands:
  start:
    description: starts Bingo
  stopgame:
    description: stops the game
  createteam:
    description: creates a new team
    aliases: [ct]
  bingo:
    description: see all the items you have to get
  backpack:
    description: see the backpack of your team
    aliases: [bp]
  join:
    description: join
  settings:
    description: settings
  top:
    description: top
  leaveteam:
    description: leave
